Communication
String Communication::_message
Referenced by LatestMessage, ReceiveMessage.
bool Communication::_newMessage
Referenced by LatestMessage, MessageIsNew, ReceiveMessage.
Communication::Communication()
Communication::~Communication()
void Communication::SendMessage(String)
References MMStateMachine::CurrentState, StateMachine.
Referenced by GCodeInterpreter::ExecuteStep, GCodeInterpreter::Interpret, GCodeInterpreter::M03_SetUp, GCodeInterpreter::M05_SetUp, SendReply, MMStateMachine::SetErrorState, BLDCDriver::setSpeed, MMStateMachine::TryUpdateState.
void Communication::ReceiveMessage(String)
References _message, _newMessage.
String Communication::LatestMessage()
References _message, _newMessage.
void Communication::SendReply()
References SendMessage, STANDARD_REPLY_COMMAND.
Referenced by GCodeInterpreter::ExecutionIsComplete, MMStateMachine::TryUpdateState.
bool Communication::MessageIsNew()
References _newMessage.