MMStateMachine
uint8_t MMStateMachine::_state
Referenced by CurrentState, MMStateMachine, Reset, SetErrorState, SetExecutionState, SetIdleState, TryUpdateState.
bool MMStateMachine::_EndstopEn
Referenced by MMStateMachine, ResolveEndstops, SetEndstopsEn.
uint8_t MMStateMachine::StateChangeLookupTable[4][4][4][4]
Referenced by TryUpdateState.
bool MMStateMachine::_endstopArray[NO_OF_ENDSTOPS][NO_OF_ENDSTOPS]
Referenced by MMStateMachine, ResolveEndstops, returnEndstop.
MMStateMachine::MMStateMachine()
References _endstopArray, _EndstopEn, _state, INIT_STATE, NO_OF_ENDSTOPS.
MMStateMachine::~MMStateMachine()
void MMStateMachine::MMSafetyBegin()
References TABLE_FLIP_ENDSTOP_1, TABLE_FLIP_ENDSTOP_2, TABLE_HOLD_LEFT_ENDSTOP_1, TABLE_HOLD_LEFT_ENDSTOP_2, TABLE_HOLD_LEFT_ENDSTOP_3, TABLE_HOLD_LEFT_ENDSTOP_4, TABLE_HOLD_MAX_ENDSTOP, TABLE_HOLD_RIGHT_ENDSTOP_1, TABLE_HOLD_RIGHT_ENDSTOP_2, TABLE_HOLD_RIGHT_ENDSTOP_3, TABLE_HOLD_RIGHT_ENDSTOP_4, TABLE_LEVEL_ENDSTOP, TABLE_LEVEL_PROBE, TABLE_LEVEL_SENSOR, X_MAX_ENDSTOP_PIN, X_MIN_ENDSTOP_PIN, Y_MAX_ENDSTOP_PIN, Y_MIN_ENDSTOP_PIN, Z_MAX_ENDSTOP_PIN, Z_MIN_ENDSTOP_PIN.
uint8_t MMStateMachine::CurrentState()
References _state.
Referenced by Communication::SendMessage.
bool MMStateMachine::TryUpdateState(String)
References _state, COMMUNICATION_TEST_COMMAND, ERROR_COMMAND, ERROR_STATE, MMcomm, RESET_COMMAND, Communication::SendMessage, Communication::SendReply, STANDARD_REPLY_COMMAND, StateChangeLookupTable, UNEXPECTED_STATE_ERROR.
void MMStateMachine::SetErrorState(String)
References _state, ERROR_STATE, MMcomm, Communication::SendMessage.
Referenced by GCodeInterpreter::ExecuteStep, GCodeInterpreter::PrepareForExecution.
void MMStateMachine::SetErrorState()
References MMcomm, Communication::SendMessage, UNKNOWN_ERROR.
void MMStateMachine::SetExecutionState()
References _state, EXECUTION_STATE.
void MMStateMachine::SetIdleState()
References _state, IDLE_STATE.
Referenced by GCodeInterpreter::ExecutionIsComplete.
void MMStateMachine::Reset()
References _state, INIT_STATE.
void MMStateMachine::SetEndstopsEn(bool)
References _EndstopEn.
Referenced by GCodeInterpreter::G28_SetUp, GCodeInterpreter::PrepareForExecution.
void MMStateMachine::ResolveEndstops()
References _endstopArray, _EndstopEn, NO_OF_ENDSTOPS, SMotor::SetEnable, TABLE_FLIP_ENDSTOP_1, TABLE_FLIP_ENDSTOP_2, TABLE_HOLD_LEFT_ENDSTOP_1, TABLE_HOLD_LEFT_ENDSTOP_2, TABLE_HOLD_LEFT_ENDSTOP_3, TABLE_HOLD_LEFT_ENDSTOP_4, TABLE_HOLD_MAX_ENDSTOP, TABLE_HOLD_RIGHT_ENDSTOP_1, TABLE_HOLD_RIGHT_ENDSTOP_2, TABLE_HOLD_RIGHT_ENDSTOP_3, TABLE_HOLD_RIGHT_ENDSTOP_4, TABLE_LEVEL_ENDSTOP, TABLE_LEVEL_PROBE, TABLE_LEVEL_SENSOR, X_MAX_ENDSTOP_PIN, X_MIN_ENDSTOP_PIN, XStepper, Y_MAX_ENDSTOP_PIN, Y_MIN_ENDSTOP_PIN, YStepper, Z_MAX_ENDSTOP_PIN, Z_MIN_ENDSTOP_PIN, ZStepper.
bool MMStateMachine::returnEndstop(uint8_t)
References _endstopArray.
Referenced by GCodeInterpreter::G28_Execute.