GCodeInterpreter
float GCodeInterpreter::_G
Referenced by Clear, ExecuteStep, Interpret, PrepareForExecution.
float GCodeInterpreter::_M
Referenced by Clear, ExecuteStep, Interpret, PrepareForExecution.
float GCodeInterpreter::_X
Referenced by Clear, G00_Execute, G00_SetUp, G01_Execute, G01_SetUp, Interpret.
float GCodeInterpreter::_Y
Referenced by Clear, G00_Execute, G00_SetUp, G01_Execute, G01_SetUp, Interpret.
float GCodeInterpreter::_Z
Referenced by Clear, G00_Execute, G00_SetUp, G01_Execute, G01_SetUp, Interpret.
float GCodeInterpreter::_I
Referenced by Clear, Interpret.
float GCodeInterpreter::_J
Referenced by Clear, Interpret.
float GCodeInterpreter::_S
Referenced by Clear, ExecuteStep, Interpret, PrepareForExecution.
float GCodeInterpreter::_F
Referenced by Clear, Interpret.
float GCodeInterpreter::_U
Referenced by Clear, ExecuteStep, Interpret, PrepareForExecution.
float GCodeInterpreter::_P
Referenced by G04_Execute, Interpret.
float GCodeInterpreter::_LV[20][20]
Referenced by Clear, G00_Execute, G00_SetUp, G01_Execute, G01_SetUp, G28_Execute, G28_SetUp, M03_Execute, M03_SetUp, M05_Execute, M05_SetUp.
bool GCodeInterpreter::_spindleIsWorking
Referenced by ExecuteStep, GCodeInterpreter, M03_SetUp, M05_SetUp, PrepareForExecution.
uint32_t GCodeInterpreter::_numberOfStepsRequired
uint32_t GCodeInterpreter::_currentStep
float GCodeInterpreter::_XPosition
Referenced by G00_Execute, G00_SetUp, G01_Execute, G01_SetUp, G28_Execute, GCodeInterpreter, Interpret.
float GCodeInterpreter::_YPosition
Referenced by G00_Execute, G00_SetUp, G01_Execute, G01_SetUp, G28_Execute, GCodeInterpreter, Interpret.
float GCodeInterpreter::_ZPosition
Referenced by G00_Execute, G00_SetUp, G01_Execute, G01_SetUp, GCodeInterpreter, Interpret.
float GCodeInterpreter::_RotPosition
float GCodeInterpreter::_TablePosition
uint16_t GCodeInterpreter::_TableSpeed
uint16_t GCodeInterpreter::_TableRotationSpeed
uint16_t GCodeInterpreter::_SpindleSpeed
Referenced by ExecuteStep, GCodeInterpreter, M03_Execute, M03_SetUp, M05_SetUp, PrepareForExecution.
uint16_t GCodeInterpreter::_CartesianSpeed
uint32_t GCodeInterpreter::time
Referenced by ExecuteStep, G04_Execute, G04_SetUp, M03_Execute, M03_SetUp, M05_Execute, M05_SetUp, PrepareForExecution.
void GCodeInterpreter::SetSteppersEn(bool)
References SMotor::SetEnable, XStepper, YStepper, ZStepper.
Referenced by ExecutionIsComplete, PrepareForExecution.
void GCodeInterpreter::G00_SetUp()
References _LV, _X, _XPosition, _Y, _YPosition, _Z, _ZPosition.
Referenced by PrepareForExecution.
void GCodeInterpreter::G01_SetUp()
References _LV, _X, _XPosition, _Y, _YPosition, _Z, _ZPosition.
Referenced by PrepareForExecution.
void GCodeInterpreter::G28_SetUp()
References _LV, MMStateMachine::SetEndstopsEn, StateMachine.
Referenced by PrepareForExecution.
void GCodeInterpreter::G04_SetUp()
References time.
Referenced by PrepareForExecution.
void GCodeInterpreter::M03_SetUp()
References _LV, _spindleIsWorking, _SpindleSpeed, BLDC_MINIMUM_SPEED_VALUE, MMcomm, Communication::SendMessage, time.
Referenced by PrepareForExecution.
void GCodeInterpreter::M05_SetUp()
References _LV, _spindleIsWorking, _SpindleSpeed, MMcomm, Communication::SendMessage, time.
Referenced by PrepareForExecution.
void GCodeInterpreter::G00_Execute()
References _LV, _X, _XPosition, _Y, _YPosition, _Z, _ZPosition, ExecutionIsComplete, RAPID_SPEED, SMotor::Step, XStepper, YStepper, ZStepper.
Referenced by ExecuteStep.
void GCodeInterpreter::G01_Execute()
References _LV, _X, _XPosition, _Y, _YPosition, _Z, _ZPosition, ExecutionIsComplete, SMotor::Step, WORKING_SPEED, XStepper, YStepper, ZStepper.
Referenced by ExecuteStep.
void GCodeInterpreter::G04_Execute()
References _P, ExecutionIsComplete, time.
Referenced by ExecuteStep.
void GCodeInterpreter::M03_Execute()
References _LV, _SpindleSpeed, BLDC_ACCELERATION_SPEED, BLDC_ACCELERATION_VALUE, ExecutionIsComplete, BLDCDriver::setSpeed, spindle, time.
Referenced by ExecuteStep.
void GCodeInterpreter::M05_Execute()
References _LV, BLDC_ACCELERATION_SPEED, BLDC_ACCELERATION_VALUE, BLDC_MINIMUM_SPEED_VALUE, ExecutionIsComplete, BLDCDriver::setSpeed, spindle, time.
Referenced by ExecuteStep.
void GCodeInterpreter::U01_Execute()
void GCodeInterpreter::G28_Execute()
References _LV, _XPosition, _YPosition, ExecutionIsComplete, GO_HOME_SLOW_SPEED, GO_HOME_SPEED, MMStateMachine::returnEndstop, StateMachine, SMotor::Step, XStepper, YStepper.
Referenced by ExecuteStep.
GCodeInterpreter::GCodeInterpreter()
References _spindleIsWorking, _SpindleSpeed, _XPosition, _YPosition, _ZPosition, BLDC_DEFAULT_SPEED, Clear.
GCodeInterpreter::~GCodeInterpreter()
void GCodeInterpreter::PrepareForExecution()
References _G, _M, _S, _spindleIsWorking, _SpindleSpeed, _U, Clear, DUMMY_VALUE, G00_SetUp, G01_SetUp, G04_SetUp, G28_SetUp, M03_SetUp, M05_SetUp, SMotor::SetEnable, MMStateMachine::SetEndstopsEn, MMStateMachine::SetErrorState, SetSteppersEn, StateMachine, TableStepper, time, UNKNOWN_GCODE_ERROR.
void GCodeInterpreter::ExecuteStep()
References _G, _M, _S, _spindleIsWorking, _SpindleSpeed, _U, BLDC_ACCELERATION_VALUE, Clear, DUMMY_VALUE, ExecutionIsComplete, G00_Execute, G01_Execute, G04_Execute, G28_Execute, M03_Execute, M05_Execute, MMcomm, Communication::SendMessage, MMStateMachine::SetErrorState, BLDCDriver::setSpeed, spindle, StateMachine, time.
bool GCodeInterpreter::Interpret(String)
References _F, _G, _I, _J, _M, _P, _S, _U, _X, _XPosition, _Y, _YPosition, _Z, _ZPosition, DUMMY_VALUE, INTERPRETATION_FAILED_WARNING, MMcomm, Communication::SendMessage.
void GCodeInterpreter::Clear()
References _F, _G, _I, _J, _LV, _M, _S, _U, _X, _Y, _Z, DUMMY_VALUE.
Referenced by ExecuteStep, ExecutionIsComplete, GCodeInterpreter, PrepareForExecution.
void GCodeInterpreter::ExecutionIsComplete()
References Clear, MMcomm, Communication::SendReply, MMStateMachine::SetIdleState, SetSteppersEn, StateMachine.
Referenced by ExecuteStep, G00_Execute, G01_Execute, G04_Execute, G28_Execute, M03_Execute, M05_Execute.