BLDCDriver
Servo BLDCDriver::_bldc
Referenced by init, setSpeed.
BLDCDriver::BLDCDriver()
BLDCDriver::~BLDCDriver()
void BLDCDriver::init()
References _bldc, setSpeed, SPINDLE_SIGNAL_PIN.
void BLDCDriver::setSpeed(uint16_t)
References _bldc, BLDC_MAXIMUM_SPEED_VALUE, BLDC_MINIMUM_SPEED_VALUE, MMcomm, Communication::SendMessage.
Referenced by GCodeInterpreter::ExecuteStep, init, GCodeInterpreter::M03_Execute, GCodeInterpreter::M05_Execute.