SMotor
uint8_t SMotor::_dir_pin
Referenced by Init, Step.
uint8_t SMotor::_step_pin
Referenced by Init, Step.
uint8_t SMotor::_enable_pin
Referenced by Init, SetEnable.
bool SMotor::_enable
Referenced by GetBoolEnable, Init, SetEnable, SMotor, Step.
long SMotor::_abs_possition
Referenced by GetAbsPossition, SMotor.
SMotor::SMotor()
References _abs_possition, _enable.
SMotor::~SMotor()
void SMotor::Init(uint8_t, uint8_t, uint8_t)
References _dir_pin, _enable, _enable_pin, _step_pin.
Referenced by RoTable::init.
long SMotor::GetAbsPossition()
References _abs_possition.
bool SMotor::GetBoolEnable()
References _enable.
void SMotor::SetEnable(bool)
References _enable, _enable_pin.
Referenced by GCodeInterpreter::PrepareForExecution, MMStateMachine::ResolveEndstops, GCodeInterpreter::SetSteppersEn.
void SMotor::Step(int DIR)
References _dir_pin, _enable, _step_pin.
Referenced by GCodeInterpreter::G00_Execute, GCodeInterpreter::G01_Execute, GCodeInterpreter::G28_Execute.